import { BuildingConfig, BuildingType } from '../types/game';

export const BUILDING_CONFIGS: Record<BuildingType, BuildingConfig> = {
  heaven_temple: {
    name: 'Храм Небес',
    cost: 300,
    health: 400,
    buildTime: 30,
    resourceGeneration: 1,
    canProduce: ['servant', 'priest', 'angel'],
    ascii: ['╔═══╗', '║ ☨ ║', '╚═══╝'],
    width: 5,
    height: 3,
    description: 'Главное здание ангелов',
  },
  heart_heaven: {
    name: 'Сердце Небес',
    cost: 150,
    health: 300,
    buildTime: 25,
    canProduce: ['paladin', 'seraphim'],
    ascii: ['╭───╮', '│ ✦ │', '╰───╯'],
    width: 5,
    height: 3,
    description: 'Производит элитные войска',
  },
  holy_altar: {
    name: 'Святой Алтарь',
    cost: 80,
    health: 200,
    buildTime: 15,
    resourceGeneration: 3,
    ascii: ['┌─┐', '│+│', '└─┘'],
    width: 3,
    height: 3,
    description: 'Генератор ресурсов',
  },
  holy_relic: {
    name: 'Святые Мощи',
    cost: 70,
    health: 250,
    buildTime: 12,
    ascii: ['⊕', '║', '⊕'],
    width: 1,
    height: 3,
    description: 'Оборонная турель',
  },
  enlightenment_altar: {
    name: 'Алтарь Просвещения',
    cost: 130,
    health: 280,
    buildTime: 20,
    ascii: ['┏━━┓', '┃◈◈┃', '┗━━┛'],
    width: 4,
    height: 3,
    description: 'Центр исследований',
  },
  hell_sanctuary: {
    name: 'Пристанище Ада',
    cost: 300,
    health: 400,
    buildTime: 30,
    resourceGeneration: 1,
    canProduce: ['slave', 'cultist', 'demon'],
    ascii: ['╔═══╗', '║ ⛤ ║', '╚═══╝'],
    width: 5,
    height: 3,
    description: 'Главное здание демонов',
  },
  heart_hell: {
    name: 'Сердце Ада',
    cost: 150,
    health: 300,
    buildTime: 25,
    canProduce: ['hellknight', 'infernal'],
    ascii: ['╭───╮', '│ ♆ │', '╰───╯'],
    width: 5,
    height: 3,
    description: 'Производит элитные войска',
  },
  dark_altar: {
    name: 'Темный Алтарь',
    cost: 80,
    health: 200,
    buildTime: 15,
    resourceGeneration: 3,
    ascii: ['┌─┐', '│⚝│', '└─┘'],
    width: 3,
    height: 3,
    description: 'Генератор ресурсов',
  },
  dark_relic: {
    name: 'Темные Реликвии',
    cost: 70,
    health: 250,
    buildTime: 12,
    ascii: ['⊗', '║', '⊗'],
    width: 1,
    height: 3,
    description: 'Оборонная турель',
  },
  corruption_altar: {
    name: 'Алтарь Искажения',
    cost: 130,
    health: 280,
    buildTime: 20,
    ascii: ['┏━━┓', '┃⛧⛧┃', '┗━━┛'],
    width: 4,
    height: 3,
    description: 'Центр исследований',
  },
};
