import { UnitConfig, UnitType } from '../types/game';

export const UNIT_CONFIGS: Record<UnitType, UnitConfig> = {
  servant: {
    name: 'Служитель',
    cost: 15,
    health: 100,
    damage: 5,
    range: 30,
    attackSpeed: 1.5,
    initialSquadSize: 1,
    maxSquadSize: 1,
    buildTime: 10,
    ascii: '⛪',
    description: 'Строитель и ремонтник',
  },
  priest: {
    name: 'Священник',
    cost: 40,
    health: 120,
    damage: 15,
    range: 150,
    attackSpeed: 1.2,
    initialSquadSize: 1,
    maxSquadSize: 4,
    buildTime: 15,
    ascii: '†',
    description: 'Слабый начальный отряд',
  },
  angel: {
    name: 'Ангел',
    cost: 72,
    health: 960,
    damage: 120,
    range: 200,
    attackSpeed: 1.0,
    initialSquadSize: 1,
    maxSquadSize: 1,
    buildTime: 25,
    ascii: '☨',
    description: 'Мощный одиночный юнит',
  },
  paladin: {
    name: 'Паладин',
    cost: 80,
    health: 180,
    damage: 22.5,
    range: 40,
    attackSpeed: 1.0,
    initialSquadSize: 4,
    maxSquadSize: 7,
    buildTime: 20,
    ascii: '⚔',
    description: 'Ближний бой',
  },
  seraphim: {
    name: 'Серафим Света',
    cost: 100,
    health: 150,
    damage: 40,
    range: 180,
    attackSpeed: 1.1,
    initialSquadSize: 3,
    maxSquadSize: 5,
    buildTime: 22,
    ascii: '✦',
    description: 'Дальний бой молниями',
  },
  slave: {
    name: 'Раб',
    cost: 15,
    health: 100,
    damage: 5,
    range: 30,
    attackSpeed: 1.5,
    initialSquadSize: 1,
    maxSquadSize: 1,
    buildTime: 10,
    ascii: '⛧',
    description: 'Строитель и ремонтник',
  },
  cultist: {
    name: 'Культист',
    cost: 40,
    health: 120,
    damage: 15,
    range: 150,
    attackSpeed: 1.2,
    initialSquadSize: 1,
    maxSquadSize: 4,
    buildTime: 15,
    ascii: '⚝',
    description: 'Слабый начальный отряд',
  },
  demon: {
    name: 'Демон',
    cost: 72,
    health: 960,
    damage: 120,
    range: 200,
    attackSpeed: 1.0,
    initialSquadSize: 1,
    maxSquadSize: 1,
    buildTime: 25,
    ascii: '⛤',
    description: 'Мощный одиночный юнит',
  },
  hellknight: {
    name: 'Рыцарь Ада',
    cost: 80,
    health: 180,
    damage: 22.5,
    range: 40,
    attackSpeed: 1.0,
    initialSquadSize: 4,
    maxSquadSize: 7,
    buildTime: 20,
    ascii: '⚡',
    description: 'Ближний бой',
  },
  infernal: {
    name: 'Инфернал',
    cost: 100,
    health: 150,
    damage: 40,
    range: 180,
    attackSpeed: 1.1,
    initialSquadSize: 3,
    maxSquadSize: 5,
    buildTime: 22,
    ascii: '♆',
    description: 'Дальний бой огнем',
  },
};
